//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bankir_CurrencyExchangeAccounting
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BankirBDEntities5 : DbContext
    {
        private static BankirBDEntities5 _context = new BankirBDEntities5();
        public BankirBDEntities5()
            : base("name=BankirBDEntities5")
        {
        }

        public static BankirBDEntities5 GetContext()
        {
            if (_context == null)
            {
                _context = new BankirBDEntities5();

            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    

        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<CurrencyAccount> CurrencyAccounts { get; set; }
        public virtual DbSet<CurrencyCours> CurrencyCourses { get; set; }
        public virtual DbSet<Operation> Operations { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TypeOfCurrency> TypeOfCurrencies { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
