//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bankir_CurrencyExchangeAccounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyCours
    {
        public int id { get; set; }
        public System.DateTime DateOfCourse { get; set; }
        public int CurrencyID { get; set; }
        public string ZaSkolko { get; set; }
        public decimal CourseRF { get; set; }
        public decimal CourseSale { get; set; }
        public decimal CourseBuy { get; set; }
    
        public virtual TypeOfCurrency TypeOfCurrency { get; set; }
    }
}
