//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bankir_CurrencyExchangeAccounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public int id { get; set; }
        public string TypeOfOperation { get; set; }
        public System.DateTime date { get; set; }
        public int AccountID { get; set; }
        public decimal Sum { get; set; }
    
        public virtual CurrencyAccount CurrencyAccount { get; set; }
    }
}
